export const ENV_VARS = {

    SMTP_PORT: 'SMTP_PORT',
    SMTP_HOST: 'SMTP_HOST',
    SMTP_USER: 'SMTP_USER',
    SMTP_PASSWORD:'SMTP_PASSWORD',
    SMTP_FROM:'SMTP_FROM',

    APP_DOMAIN:'APP_DOMAIN',
    JWT_SECRET:'JWT_SECRET',
}     

export const CLOUDINARY = {
    CLOUD_NAME: 'CLOUD_NAME',
    API_KEY: 'API_KEY',
    API_SECRET: 'API_SECRET',
  };